# description of this workflow, can be anything you want
name: Package addon

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
      - 'assets/*'
      - 'README.md'
# a workflow is built up as jobs, and within these jobs are steps
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package
        uses: BigWigsMods/packager@master
